name: 'Refresh conda-lock'

description: 'Regenerate fully reproducible conda-lock.yml files for conda environments.'

author: 'GitHub'

branding:  # https://haya14busa.github.io/github-action-brandings/
  icon: 'lock'
  color: 'green'

inputs:
  file:
    description: 'Path to the conda environment specification(s)'
    required: true
    default: 'environment.yml'
  platform:
    description: 'The platforms to generate the lockfile for'
    required: false
    default: 'linux-64'

runs:
  using: "composite"
  steps:
    # Setup Python environment
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install conda-lock library and show version
    - name: Install conda-lock
      run: python -m pip install conda-lock
      shell: bash -l {0}

    # Print debugging information
    - name: Print debug info
      run: |
        conda-lock --version
        echo Locking ${{ inputs.file }} file for ${{ inputs.platform }} platform.
      shell: bash -l {0}

    # Run conda-lock
    - name: Run conda-lock
      run: |
        rm --force conda-lock.yml
        conda-lock lock --file ${{ inputs.file }} --platform ${{ inputs.platform }}
      shell: bash -l {0}

    # Print contents of lockfile
    - name: Inspect lockfile
      run: cat conda-lock.yml
      shell: bash -l {0}

    # Commit the change to the PR branch if any changes
    - name: Commit condalock files to PR
      run: |
        if [[ $(git ls-files --modified --others) ]]; then
          git config --global user.name 'actions-bot'
          git config --global user.email '58130806+actions-bot@users.noreply.github.com'
          git commit --all --message "[condalock-command] autogenerated conda-lock files"
          git push
        fi
      shell: bash -l {0}
